# Generated by Django 2.0.6 on 2019-09-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('RealName', models.CharField(max_length=200)),
                ('AccountNumber', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Breed', models.CharField(max_length=200)),
                ('Color', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=200)),
            ],
        ),
    ]
